modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"
[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
updateJSONURL = "https://api.modrinth.com/updates/confluence-delight/forge_updates.json" #optional
displayURL = "https://modrinth.com/project/confluence-delight" #optional
authors = "${mod_authors}" #optional
description = '''${mod_description}'''
[[mixins]]
config = "${mod_id}.mixins.json"
[[dependencies."${mod_id}"]] #optional
modId = "neoforge"
type = "required"
versionRange = "${neo_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "confluence"
type = "required"
versionRange = "[1.0.2-hotfix,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "farmersdelight"
type = "required"
versionRange = "[1.2.7,)"
ordering = "AFTER"
side = "BOTH"